#   (                                     )  (     
#   )\ )   )                 )         ( /(  )\ )  
#  (()/(( /(              ( /(     (   )\())(()/(  
#   /(_))\()) (  (  `  )  )\()) (  )( ((_)\  /(_)) 
#  (_))((_)\  )\ )\ /(/( ((_)\  )\(()\  ((_)(_))   
#  | _ \ |(_)((_|(_|(_)_\| |(_)((_)((_)/ _ \/ __|  
#  |  _/ ' \/ _ (_-< '_ \) ' \/ _ \ '_| (_) \__ \  
#  |_| |_||_\___/__/ .__/|_||_\___/_|  \___/|___/  
#                |_|                                                                                                                         ███    ███                         
#

[window]
opacity = 0.75
[colors]
[colors.primary]
background = "#15141b"
foreground = "#bdbdbd"

[colors.normal]
black   = "#15141b"
red     = "#c55858"
green   = "#54c59f"
yellow  = "#c7a06f"
blue    = "#8464c6"
magenta = "#c17ac8"
cyan    = "#6cb2c7"
white   = "#bdbdbd"

[colors.bright]
black   = "#6d6d6d"
red     = "#c55858"
green   = "#54c59f"
yellow  = "#c7a06f"
blue    = "#8464c6"
magenta = "#c17ac8"
cyan    = "#6cb2c7"
white   = "#bdbdbd"

[colors.cursor]
text   = "#15141b"
cursor = "#8464c6"

#      )                                     
#   ( /(  (  (               )        )      
#   )\()) )\ )\ )  (      ( /(     ( /(      
#  ((_)\ ((_|()/(  )\  (  )\()) (  )\()) (   
#    ((_) _  ((_))((_) )\((_)\  )\((_)\  )\  
#   / _ \| | _| |_ | |((_) |(_)((_) |(_)((_) 
#  | (_) | / _` | || / _ \ '_ Y _ \ '_ Y _ \ 
#   \___/|_\__,_|\__/\___/_.__|___/_.__|___/ 
#                                            
#  25-01-26
