#   (                                     )  (     
#   )\ )   )                 )         ( /(  )\ )  
#  (()/(( /(              ( /(     (   )\())(()/(  
#   /(_))\()) (  (  `  )  )\()) (  )( ((_)\  /(_)) 
#  (_))((_)\  )\ )\ /(/( ((_)\  )\(()\  ((_)(_))   
#  | _ \ |(_)((_|(_|(_)_\| |(_)((_)((_)/ _ \/ __|  
#  |  _/ ' \/ _ (_-< '_ \) ' \/ _ \ '_| (_) \__ \  
#  |_| |_||_\___/__/ .__/|_||_\___/_|  \___/|___/  
#                |_|                                                                                                                         ███    ███                         
#

[window]
opacity = 0.75
[colors]
[colors.primary]
background = "#0f191c"
foreground = "#409931"

[colors.normal]
black   = "#0f191c"
red     = "#688060"
green   = "#faff00"
yellow  = "#90d762"
blue    = "#11ff25"
magenta = "#c1ff8a"
cyan    = "#4f7e7e"
white   = "#409931"

[colors.bright]
black   = "#ffd700"
red     = "#688060"
green   = "#faff00"
yellow  = "#90d762"
blue    = "#11ff25"
magenta = "#c1ff8a"
cyan    = "#4f7e7e"
white   = "#507350"

[colors.cursor]
text   = "#0f191c"
cursor = "#11ff25"

#      )                                     
#   ( /(  (  (               )        )      
#   )\()) )\ )\ )  (      ( /(     ( /(      
#  ((_)\ ((_|()/(  )\  (  )\()) (  )\()) (   
#    ((_) _  ((_))((_) )\((_)\  )\((_)\  )\  
#   / _ \| | _| |_ | |((_) |(_)((_) |(_)((_) 
#  | (_) | / _` | || / _ \ '_ Y _ \ '_ Y _ \ 
#   \___/|_\__,_|\__/\___/_.__|___/_.__|___/ 
#                                            
#  25-01-26
