#   (                                     )  (     
#   )\ )   )                 )         ( /(  )\ )  
#  (()/(( /(              ( /(     (   )\())(()/(  
#   /(_))\()) (  (  `  )  )\()) (  )( ((_)\  /(_)) 
#  (_))((_)\  )\ )\ /(/( ((_)\  )\(()\  ((_)(_))   
#  | _ \ |(_)((_|(_|(_)_\| |(_)((_)((_)/ _ \/ __|  
#  |  _/ ' \/ _ (_-< '_ \) ' \/ _ \ '_| (_) \__ \  
#  |_| |_||_\___/__/ .__/|_||_\___/_|  \___/|___/  
#                  |_|                                                                                                                         ███    ███                         
#
#  Based on the Matrix Base16 colorscheme
#
#


accent = "#11ff25"
active_border_color = "#11ff25"
active_tab_background = "#11ff25"
cursor = "#507350"
foreground = "#507350"
background = "#0f191c"
selection_foreground = "#0f191c"
selection_background = "#11ff25"

color0 = "#0f191c"
color1 = "#688060"
color2 = "#faff00"
color3 = "#90d762"
color4 = "#11ff25"
color5 = "#c1ff8a"
color6 = "#4f7e7e"
color7 = "#409931"
color8 = "#ffd700"
color9 = "#688060"
color10 = "#faff00"
color11 = "#90d762"
color12 = "#11ff25"
color13 = "#c1ff8a"
color14 = "#4f7e7e"
color15 = "#507350"


#      )                                     
#   ( /(  (  (               )        )      
#   )\()) )\ )\ )  (      ( /(     ( /(      
#  ((_)\ ((_|()/(  )\  (  )\()) (  )\()) (   
#    ((_) _  ((_))((_) )\((_)\  )\((_)\  )\  
#   / _ \| | _| |_ | |((_) |(_)((_) |(_)((_) 
#  | (_) | / _` | || / _ \ '_ Y _ \ '_ Y _ \ 
#   \___/|_\__,_|\__/\___/_.__|___/_.__|___/ 
#                                            
#  25-01-26
