#   (                                     )  (     
#   )\ )   )                 )         ( /(  )\ )  
#  (()/(( /(              ( /(     (   )\())(()/(  
#   /(_))\()) (  (  `  )  )\()) (  )( ((_)\  /(_)) 
#  (_))((_)\  )\ )\ /(/( ((_)\  )\(()\  ((_)(_))   
#  | _ \ |(_)((_|(_|(_)_\| |(_)((_)((_)/ _ \/ __|  
#  |  _/ ' \/ _ (_-< '_ \) ' \/ _ \ '_| (_) \__ \  
#  |_| |_||_\___/__/ .__/|_||_\___/_|  \___/|___/  
#                  |_|                                                                                                                         ███    ███                         
#
#  Based on the Matrix Base16 colorscheme
#
#


accent = "#8464c6"
active_border_color = "#8464c6"
active_tab_background = "#8464c6"
cursor = "#8464c6"
foreground = "#bdbdbd"
background = "#15141b"
selection_foreground = "#bdbdbd"
selection_background = "#29263c"

color0 = "#15141b"
color1 = "#c55858"
color2 = "#54c59f"
color3 = "#c7a06f"
color4 = "#8464c6"
color5 = "#c17ac8"
color6 = "#6cb2c7"
color7 = "#bdbdbd"
color8 = "#6d6d6d"
color9 = "#c55858"
color10 = "#54c59f"
color11 = "#c7a06f"
color12 = "#8464c6"
color13 = "#c17ac8"
color14 = "#6cb2c7"
color15 = "#bdbdbd"


#      )                                     
#   ( /(  (  (               )        )      
#   )\()) )\ )\ )  (      ( /(     ( /(      
#  ((_)\ ((_|()/(  )\  (  )\()) (  )\()) (   
#    ((_) _  ((_))((_) )\((_)\  )\((_)\  )\  
#   / _ \| | _| |_ | |((_) |(_)((_) |(_)((_) 
#  | (_) | / _` | || / _ \ '_ Y _ \ '_ Y _ \ 
#   \___/|_\__,_|\__/\___/_.__|___/_.__|___/ 
#                                            
#  25-01-26
